---
apiVersion: v1
kind: Template
metadata:
  name: prometheus-operator
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: prometheus
  spec:
    channel: preview
    name: prometheus
    source: rh-operators
parameters:
- name: IMAGE_TAG
  value: none
  displayName: dummy image tag to workaround saasherder IMAGE_TAG override

